### ISSUE TITLE
Error when running setup script

### ISSUE THREAD

**Issue by rovwtr** [facebookresearch/DeltaCNN#11]
Dear,

When attempting to install DeltaCNN via the setup.py, the following error occurs:

"ModuleNotFoundError: No module named 'deltacnn.cuda'"

Both on Linux and Windows this error occurs. Al packages were installed as required but the error persisted.
Could you please help us?

With kind regards,

Ruben

**Comment by dabeschte** [comment]
Did you install cuda and set CUDA_HOME path?

It sounds to me like cuda kernels were not compiled

**Comment by sanzgadea** [comment]
Hey Ruben, 

I had the same problem at first and it is solved, like dabeschte said, by making sure you have the correct Cuda version installed and by setting the CUDA_HOME path.

You can set the CUDA_HOME path in a Windows terminal, in my case I am using anaconda, by:

`setx CUDA_HOME "your_cuda_path"`

By default, the CUDA Toolkit will be installed in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA. Take note of the specific version number in the folder name (e.g., v11.8).

Lastly, you can check if it is working with:

`import torch
torch.cuda.is_available()`

As per this post: https://stackoverflow.com/questions/48152674/how-do-i-check-if-pytorch-is-using-the-gpu
