### ISSUE TITLE
ImportError: /home/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9-linux-x86_64.egg/deltacnn/cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by kai981** [facebookresearch/DeltaCNN#5]
Hi, I am trying to use the mobilenetv2_deltacnn provided to do some inferencing, but encountered the following error: 

Traceback (most recent call last):
  File "/home/example/mobilenetv2_inference.py", line 48, in <module>
    from deltacnn.sparse_layers import DCBackend, DCConv2d, DCThreshold
  File "/home/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9-linux-x86_64.egg/deltacnn/__init__.py", line 6, in <module>
    from .cuda_kernels import sparse_conv, sparse_deconv, sparse_pooling
  File "/home/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9-linux-x86_64.egg/deltacnn/cuda_kernels.py", line 7, in <module>
    from deltacnn.cuda import sparse_conv_bias_wrapper_masked, sparse_deconv_bias_wrapper_masked
ImportError: /home/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9-linux-x86_64.egg/deltacnn/cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

I am using PyTorch 1.11.0 and CUDA 11.3. 
Could you please advice on how to resolve this? Thank you!

**Comment by dabeschte** [comment]
Hey!
Looks like there was an error in the setup. Please reinstall the package and filter the logs for error messages

**Comment by kai981** [comment]
It works after reinstalling, thank you!
